#!/usr/bin/env bash

# we want to kill proccess at the end
# set -o errexit
set -o nounset

#---------------------------------------------------------------------

readonly GETH_PATH="${HOME}/eth_wallets/go-ethereum"
readonly LOGS_PATH="${HOME}/geth_logs/log00.dat"

readonly TEST_NETWORK=1

readonly RPC_ENABLE=0
# RPC options
readonly rpcPort="8882"
readonly rpcCorsDomain="localhost"

# Inter process communication is enabled as default
readonly IPC_DISABLE=0
readonly IPCFILE_PATH="${HOME}/ipc/geth.ipc"

readonly CONSOLE_MODE=1

readonly MINING_MODE=0
readonly MINING_THREADS=4


# 0=silenct, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=debug detail
readonly VERBOSITY=4

#---------------------------------------------------------------------

create_missing_dirs() {
	# get rid of file name
	local dir=$(echo $1 | rev | cut -d/ -f 2- | rev)
	if [[ ! -d $dir ]]
	then
		echo "Creating path: ${dir}"
		mkdir -p $dir
	fi
}
create_missing_dirs $LOGS_PATH
create_missing_dirs $IPCFILE_PATH

#---------------------------------------------------------------------

#declare -a geth_options=("--syncmode full" " --cache 4096")
declare -a geth_options=("--syncmode full" " --cache 2048")


# append verbosity level	
geth_options=("${geth_options[@]}" "--verbosity ${VERBOSITY}")

if [[ ${IPC_DISABLE} == 0 ]]
then
	# default admin,debug,eth,miner,net,personal,shh,txpool,web3
	ipcAPI="admin,debug,eth,miner,net,web3,personal"
#		"--ipcapi=${ipcAPI}"		\
	geth_options=(${geth_options[@]}	\
		"--ipcpath ${IPCFILE_PATH}"	\
	)
else
	# append --ipcdisable option to array	
	geth_options=(${geth_options[@]}	\
		"--ipcdisable"			\
	)

fi

if [[ ${RPC_ENABLE} == 1 ]]
then
	# RPC additional options
	rpcAPI="web3,db,net,eth"

	# append rpc options
	geth_options=(${geth_options[@]}		\
		"--rpc"					\
		"--rpcport=${rpcPort}"			\
		"--rpccorsdomain=${rpcCorsDomain}"	\
		"--rpcapi=${rpcAPI}"			\
		)
fi

if [[ ${TEST_NETWORK} == 1 ]]
then
	networkID=3 	# Ropsten testnet

	# append testnet options
	geth_options=(${geth_options[@]}		\
		"--testnet" 				\
		"--networkid=$networkID" 		\
		)

fi

if [[ ${MINING_MODE} == 1 ]]
then
	miner_threads=3
	rwd_address="0x4283bc4327eae94f58a08689648f1d7c578156a0"  # Public address for block mining rewards

	# append testnet options
	geth_options=(${geth_options[@]}		\
		"--mine" 				\
		"--minerthreads=${MINING_THREADS}" 	\
		"--etherbase=${rwd_address}"		\
		)
fi

#---------------------------------------------------------------------

echo "Geth command: ${GETH_PATH}/build/bin/geth  ${geth_options[@]}"
set -x
"${GETH_PATH}/build/bin/geth" "${geth_options[@]}" 2>>${LOGS_PATH} &
GETH_PROC_ID=$!
echo "process id: $GETH_PROC_ID"

set +x

# setting permission for ipc file
if [[ ${IPC_DISABLE} == 0 ]]
then
	# wait 2 seconds for geth.ipc to be created
	sleep 5

	# add file to ipc-eth group
	chown :ipc-eth "${IPCFILE_PATH}"

	# add ipc-eth group write permission 
	chmod g+w "${IPCFILE_PATH}"
fi


# Re-attach geth console
if [[ ${CONSOLE_MODE} == 1 ]]
then
	if [[ ${IPC_DISABLE} == 0 ]]
	then
		"${GETH_PATH}/build/bin/geth" "attach" "ipc://${IPCFILE_PATH}"
	else
		"${GETH_PATH}/build/bin/geth" "attach" "http://localhost:${rpcPort}"
	fi
fi


while :
do
	echo ""
	read -n1 -r -p "Press 'q' to kill geth and exit..." key

	if [ "$key" = 'q' ]; then
		# kill geth instance
		kill -9 "$GETH_PROC_ID" >/dev/null 2>&1;
		printf "\nBackground geth processes have exited.\n"
		break
	fi
done
